name: "clean"
version: "0.5.0"
usage: "plugin to clean no updated release"
description: "plugin to clean no updated release"
platformCommand:
  - command: "$HELM_PLUGIN_DIR/helm-clean"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"
