name: "clean"
version: "dev"
usage: "plugin to clean no updated release"
description: "plugin to clean no updated release"
useTunnel: true
platformCommand:
  - command: "$HELM_PLUGIN_DIR/helm-clean"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"
