name: "clean"
version: "0.6.0"
usage: "List/Clean out of date releases"
description: "List/Clean out of date releases"
command: "$HELM_PLUGIN_DIR/helm-clean"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"
