name: "clean"
version: "dev"
usage: "plugin to clean no updated release"
description: "plugin to clean no updated release"
useTunnel: true
platformCommand:
  - command: "$HELM_PLUGIN_DIR/bin/helm-clean"
platformHooks:
  install:
    - command: "$HELM_PLUGIN_DIR/install-binary.sh"
  update:
    - command: "$HELM_PLUGIN_DIR/install-binary.sh"
      args:
        - -u
